# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Seerr systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ seerr_identifier }}.service"
  register: seerr_service_stat

- name: Uninstall Seerr systemd services and files
  when: seerr_service_stat.stat.exists | bool
  block:
    - name: Ensure Seerr systemd service is stopped
      ansible.builtin.service:
        name: "{{ seerr_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Seerr systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ seerr_identifier }}.service"
        state: absent

    - name: Ensure Seerr support files do not exist
      ansible.builtin.file:
        path: "{{ seerr_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Seerr local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ seerr_data_path }}"
      register: seerr_data_path_deletion_result
      changed_when: seerr_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Seerr base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ seerr_base_path }}"
      register: seerr_base_path_deletion_result
      changed_when: seerr_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Seerr container network does not exist
      when: seerr_container_network_deletion_enabled
      block:
        - name: Ensure Seerr container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ seerr_container_network }}"
            state: absent
          register: seerr_network_deletion_result

        - name: Ensure Seerr container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ seerr_container_network }}
          register: seerr_network_deletion_result
          changed_when: seerr_container_network in seerr_network_deletion_result.stdout

- name: Check existence of Seerr local data path
  ansible.builtin.stat:
    path: "{{ seerr_data_path }}"
  register: seerr_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Seerr local data path
  when: seerr_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Seerr instance has been removed, some old data remains in `" + seerr_data_path + "`. Feel free to delete it."
        ]
      }}
